import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {currentAssignments,journalCalendarDays} from '../academy.js';
const source=fs.readFileSync('academy.js','utf8');
const ctx={currentAssignments,journalCalendarDays,h:x=>x||'',badge:x=>x,journalDay:'2026-10-08',journalMonth:'2026-10',parent:()=>false,parentLearningSummary:()=> 'PARENT_VIEW',current:()=> 'student',rows:()=>[],date:()=> '2026-10-08',studentSessionsPanel:()=> 'NO_SESSIONS',legacyRecords:[],empty:x=>x,btn:(label,action)=>`<button data-ac="${action}">${label}</button>`};
vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('  function learningSummary(){'),source.indexOf('  const reviewFor=',source.indexOf('  function learningSummary(){'))),ctx);
const html=ctx.learningSummary();
assert.match(html,/작성하기/);
assert.ok(html.indexOf('작성하기')<html.indexOf('NO_SESSIONS'));
ctx.parent=()=>true;
assert.equal(ctx.learningSummary(),'PARENT_VIEW');
Object.assign(ctx,{studentSessionList:()=>[],reflectionSessions:[],reflectionDay:'2026-10-08',period:'',uid:()=> 'student',h:x=>x||'',input:()=>'',area:(label,name)=>`<textarea name="${name}">${label}</textarea>`,form:(title,kind,fields)=>title+fields});
vm.runInContext(source.slice(source.indexOf('  function reflectionForm(){'),source.indexOf('  const draftKey=')),ctx);
const form=ctx.reflectionForm();
assert.equal((form.match(/ required /g)||[]).length,3);
assert.doesNotMatch(form,/교재·페이지 추가/);
for(const name of ['learned','assignment','feeling'])assert.match(form,new RegExp(`name="${name}"`));
assert.match(form,/오늘 수업/);
console.log('PASS: student reflection entry visible without sessions or homework, parent excluded, all three writing fields available');
