import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('academy.js','utf8');
const items=[{id:'reflection',kind:'reflection',status:'approved',student_id:'student',body:{},updated_at:'2026-09-30'},{id:'comment',kind:'reply',student_id:'student',body:{text:'parent comment'},updated_at:'2026-09-30'}];
const ctx={requiredReviews:[],requiredReviewsReady:true,commentReviews:[{comment_id:'comment'}],items,staff:()=>true,admin:()=>true,uid:()=> 'director',c:()=>({state:{schedules:[{studentId:'student',teacherIds:['teacher']}]}}),rows:k=>items.filter(i=>i.kind===k),visibleReflections:()=>items.filter(i=>i.kind==='reflection'),name:()=> '학생',h:String,badge:s=>s,btn:(s,a)=>`${s}:${a}`,reflectionText:()=> 'reflection text',reflectionSelection:new Set(),empty:s=>s};
vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('  const reviewFor='),source.indexOf('  function parentComments(){')),ctx);
vm.runInContext(source.slice(source.indexOf('  function notificationRail(){'),source.indexOf('  function render(route)')),ctx);
let html=ctx.notificationRail();assert.match(html,/학생 수업기록/);assert.match(html,/학부모 코멘트/);assert.match(html,/알림장 발행 필요/);assert.equal((html.match(/required-director/g)||[]).length,1);
ctx.requiredReviews=[{source_id:'reflection',lesson_id:'published',teacher_at:'yes',director_at:null},{source_id:'comment',teacher_at:'yes',director_at:null}];
html=ctx.notificationRail();assert.match(html,/학생 수업기록/);assert.match(html,/학부모 코멘트/);assert.match(html,/원장 확인 대기/);
ctx.admin=()=>false;ctx.uid=()=> 'teacher';html=ctx.notificationRail();assert.match(html,/학생 수업기록/);assert.match(html,/학부모 코멘트/,'teacher keeps seeing director-pending comment');
ctx.requiredReviews.forEach(r=>r.director_at='yes');html=ctx.notificationRail();assert.ok(!html.includes('학생 수업기록'));assert.ok(!html.includes('학부모 코멘트'));
ctx.requiredReviews[0].lesson_id=null;html=ctx.notificationRail();assert.match(html,/학생 수업기록/,'both checks alone do not replace publication');
ctx.uid=()=> 'unassigned';html=ctx.notificationRail();assert.ok(!html.includes('학생 수업기록'));assert.ok(!html.includes('학부모 코멘트'));
console.log('PASS: approval does not dismiss; both roles retain pending alerts until publication and dual checks; assigned scope and deduplicated comments');
