import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync('academy.js','utf8');
const fn=src.slice(src.indexOf('  async function moveTask('),src.indexOf('  function taskBoard('));
const items=[{id:'1',kind:'task',status:'todo',body:{priority:'high'},assignee_id:'teacher'},{id:'2',kind:'task',status:'done'}];
let writes=0;
const move=new Function('items','staff','archivedTask','save',fn+';return moveTask;')(items,()=>true,id=>id==='2',async x=>{writes++;items[0]=x;});
await move('1','doing');assert.equal(items[0].status,'doing');assert.equal(items[0].assignee_id,'teacher');assert.equal(items[0].body.priority,'high');
await move('1','doing');assert.equal(writes,1);
await move('1','done');await move('1','todo');assert.equal(items[0].status,'todo');
for(const [id,status] of [['missing','done'],['2','todo'],['1','invalid']])await assert.rejects(()=>move(id,status));
const before=structuredClone(items[0]);
const failing=new Function('items','staff','archivedTask','save',fn+';return moveTask;')(items,()=>true,()=>false,async()=>{throw Error('충돌');});
await assert.rejects(()=>failing('1','done'),/충돌/);assert.deepEqual(items[0],before);
const events={};let calls=[],busy=false;
const block=src.slice(src.indexOf('  function clearTaskDrag(){'),src.indexOf("  document.addEventListener('click',click,true);"));
const doc={querySelectorAll:()=>[],addEventListener:(name,handler)=>events[name]=handler};
new Function('document','staff','moveTask','refresh','alert',`let draggingTask=null,busy=false;${block}`)(doc,()=>true,async(...args)=>calls.push(args),()=>{},()=>{});
const board={},classes={add(){},remove(){}},card={dataset:{taskId:'1'},classList:classes,closest:()=>board};
const drag={target:{closest:s=>s==='[data-task-id]'?card:null},dataTransfer:{setData(){}},preventDefault(){}};
events.dragstart(drag);
const target={dataset:{taskStatus:'done'},classList:classes,closest:()=>board};
await events.drop({target:{closest:()=>({...target,closest:()=>({})})},preventDefault(){}});assert.equal(calls.length,0);
await events.drop({target:{closest:()=>target},preventDefault(){}});assert.deepEqual(calls,[['1','done']]);
console.log('PASS: status moves both directions, same-column no-op, archive/invalid guards, save-error preservation, board-bound drag/drop');
