import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema auth;create schema storage;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table profiles(id uuid primary key,role text,name text,login_id text,active boolean default true);
create table students(id uuid primary key references profiles(id),school_year text,school_name text);
create table lesson_records(id uuid primary key default gen_random_uuid(),student_id uuid,content text,parent_message text,student_message text,next_plan text,focus text,hidden boolean default false,is_draft boolean default false);alter table lesson_records enable row level security;grant select on lesson_records to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
grant usage on schema public,auth,storage to authenticated,service_role;
grant select,insert on storage.objects to authenticated;
`);
const sql=fs.readFileSync(new URL('../supabase/migrations/202609180001_academy_workflow.sql', import.meta.url),'utf8');
try{await db.exec(sql);}catch(e){console.error('MIGRATION ERROR',e.message,e.position,e.where);process.exit(1);}
await db.exec(fs.readFileSync(new URL('../supabase/migrations/202609180002_parent_comments.sql',import.meta.url),'utf8'));
const A='00000000-0000-4000-8000-000000000001',S='00000000-0000-4000-8000-000000000002',S2='00000000-0000-4000-8000-000000000003',P='00000000-0000-4000-8000-000000000004',T='00000000-0000-4000-8000-000000000005';
await db.query(`insert into profiles(id,role,name) values($1,'admin','원장'),($2,'student','학생1'),($3,'student','학생2'),($4,'parent','학부모'),($5,'teacher','강사')`,[A,S,S2,P,T]);
await db.query(`insert into students(id,school_year) values($1,'초6'),($2,'중2')`,[S,S2]);
await db.query(`insert into parent_students values($1,$2)`,[P,S]);
async function as(id){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function save(i){const r=await db.query('select * from academy_save($1::jsonb,$2::timestamptz)',[JSON.stringify(i),i.updated_at||null]);return r.rows[0];}
async function fails(fn,pattern){await assert.rejects(fn,pattern);}
await as(A);
let hw=await save({kind:'homework',student_id:S,title:'과제',status:'assigned',due_at:'2099-01-01',body:{}});
await as(S2);await fails(()=>save({...hw,status:'submitted'}),/접근 권한/);
await as(S);await fails(()=>save({...hw,status:'checked'}),/본인 과제/);
await fails(()=>save({...hw,status:'submitted',body:{files:[]}}),/사진/);
await fails(()=>save({kind:'assessment',student_id:S,title:'fake',body:{score:100,total:100}}),/직원/);
await as(A);let att=await save({kind:'attendance',student_id:S,status:'present',day:'2026-09-18',body:{period:'1'}});att=await save({...att,status:'present'});
let ledger=await db.query("select * from academy_points where source_key='attendance:2026-09-18'");assert.equal(ledger.rows.length,1);assert.equal(ledger.rows[0].points,1);
let exam=await save({kind:'assessment',student_id:S,title:'초등 단원평가',body:{score:10,total:10,category:'단원평가',first_attempt:true}});
assert.equal((await db.query("select points from academy_points where source_key=$1",['exam:'+exam.id])).rows[0].points,5);
exam=await save({...exam,body:{...exam.body,score:9}});assert.equal((await db.query("select points from academy_points where source_key=$1",['exam:'+exam.id])).rows[0].points,0);
let lesson=await save({kind:'lesson_draft',student_id:S,title:'수업',body:{content:'common',internal_note:'SECRET',parent_message:'PARENT_ONLY',student_message:'STUDENT_ONLY'}});
await db.query('select academy_publish($1,$2)',[lesson.id,lesson.updated_at]);
await as(S);let visible=await db.query('select kind,body from academy_items');assert(!JSON.stringify(visible.rows).includes('SECRET'));assert(!JSON.stringify(visible.rows).includes('PARENT_ONLY'));assert(JSON.stringify(visible.rows).includes('STUDENT_ONLY'));
await as(P);visible=await db.query('select kind,body from academy_items');assert(JSON.stringify(visible.rows).includes('PARENT_ONLY'));assert(!JSON.stringify(visible.rows).includes('STUDENT_ONLY'));
await as(S2);assert.equal((await db.query('select * from academy_items')).rows.length,0);
await as(A);let task=await save({kind:'task',title:'지시',status:'todo',assignee_id:T,audience:'staff',body:{priority:'normal'}});
await as(T);task=await save({...task,title:'지시 변조',status:'doing',body:{priority:'high'}});assert.equal(task.title,'지시');assert.equal(task.status,'doing');
await fails(()=>save({...task,updated_at:'2000-01-01',status:'done'}),/다른 사람/);
await as(A);
await db.exec('reset role');
await db.query("insert into lesson_records(student_id,content,parent_message,student_message) values($1,'legacy','OLD_PARENT','OLD_STUDENT')",[S]);
await as(S);assert.equal((await db.query('select * from lesson_records')).rows.length,0);
const legacy=await db.query('select * from academy_legacy_records()');assert(JSON.stringify(legacy.rows).includes('OLD_STUDENT'));assert(!JSON.stringify(legacy.rows).includes('OLD_PARENT'));
await db.query("insert into storage.objects(bucket_id,name) values('academy-private',$1)",[S+'/photo.jpg']);
hw=await save({...hw,status:'submitted',body:{files:[S+'/photo.jpg']}});
assert.equal((await db.query("select points from academy_points where source_key=$1",['homework:'+hw.id])).rows[0].points,1);
hw=await save({...hw,status:'submitted'});assert.equal((await db.query("select count(*)::int n from academy_points where source_key=$1",['homework:'+hw.id])).rows[0].n,1);
await as(A);hw=await save({...hw,status:'checked'});
await as(S);await fails(()=>save({...hw,status:'submitted'}),/본인 과제/);
await as(A);await fails(()=>save({kind:'assessment',student_id:S,title:'bad',body:{score:101,total:100}}),/점수/);
console.log('PASS: migration, RLS isolation, role checks, task assignment, optimistic locking, score deduplication, score correction, audience-separated publication');
await as(P);
const parentLesson=(await db.query("select id from academy_items where kind='lesson' limit 1")).rows[0].id;
let comment=await save({kind:'reply',student_id:S,title:'학부모 코멘트',audience:'parent',status:'sent',body:{thread:parentLesson,text:'오늘 컨디션을 살펴봐 주세요.'}});
assert.equal((await db.query('select * from academy_comment_reviews')).rows.length,0);
await fails(()=>db.query('select academy_check_comment($1,false)',[comment.id]),/직원만/);
await as(T);
assert.equal((await db.query('select * from academy_comment_notifications')).rows.length,0);
await db.query('select academy_check_comment($1,false)',[comment.id]);
await fails(()=>db.query('select academy_check_comment($1,true)',[comment.id]),/원장 확인/);
await as(A);
assert.equal((await db.query('select * from academy_comment_notifications where checked_at is null')).rows.length,2);
await db.query('select academy_check_comment($1,true)',[comment.id]);
assert.equal((await db.query('select * from academy_comment_notifications where checked_at is null')).rows.length,0);
await as(P);comment=await save({...comment,body:{...comment.body,text:'수정한 코멘트'}});
await as(T);
assert.equal((await db.query('select teacher_at from academy_comment_reviews where comment_id=$1',[comment.id])).rows[0].teacher_at,null);
await save({kind:'reply',student_id:S,title:'답글',audience:'parent',status:'sent',body:{thread:parentLesson,in_reply_to:comment.id,text:'확인했습니다.'}});
assert.ok((await db.query('select teacher_at from academy_comment_reviews where comment_id=$1',[comment.id])).rows[0].teacher_at);
await as(A);
assert.equal((await db.query('select * from academy_comment_notifications where checked_at is null')).rows.length,2);
await as(S2);assert.equal((await db.query('select * from academy_comment_reviews')).rows.length,0);
console.log('PASS: parent comment privacy, independent director checks, reply auto-check, edited comment reopens, per-event notifications');
await db.exec('reset role');
await db.exec(fs.readFileSync(new URL('../supabase/migrations/202609180003_student_ranking.sql',import.meta.url),'utf8'));
await as(P);assert.equal((await db.query('select * from academy_ranking()')).rows.length,0);
await as(S);assert.ok((await db.query('select * from academy_ranking()')).rows.length>0);
await as(A);assert.ok((await db.query('select * from academy_ranking()')).rows.length>0);
console.log('PASS: parent ranking denied, student and staff ranking retained');
await db.close();
